@extends('layout.base')

@section('page_title', 'Book Appointment')

@section('page_content')

<x-banner message="Book an appointment from anywhere" page="Book Appointment" />

<!-- ===== Booking Wizard Container ===== -->
<section class="container py-5" data-selected-service-id="{{ $selectedServiceId ?? '' }}">
    <div class="row justify-content-center">
        <div class="col-lg-10">

            <!-- Step Indicators -->
            <div class="step-indicator" id="stepIndicator">
                <!-- Generated by JS -->
            </div>

            <!-- Steps -->
            <div class="card border-0 shadow">
                <div class="card-body p-4 p-md-5">

                    <!-- Step 1: Service -->
                    <div class="step-content active" data-step="1">
                        <h4 class="mb-3">Select Services</h4>
                        <p class="text-muted">Search and choose one or more diagnostic services for your appointment.</p>
                        <div class="row g-3 mb-4 align-items-center">
                            <div class="col-md-6">
                                <div class="input-group">
                                    <span class="input-group-text"><i class="bi bi-search"></i></span>
                                    <input type="search" id="serviceSearch" class="form-control" placeholder="Search services by name, category or description">
                                </div>
                            </div>
                            <div class="col-md-6 text-md-end">
                                <select id="categoryFilter" class="form-select w-100 w-md-auto d-inline-block">
                                    <option value="">All categories</option>
                                </select>
                            </div>
                        </div>

                        <div class="card border-0 bg-light mb-3">
                            <div class="card-body p-3">
                                <button class="btn btn-outline-primary w-100 d-flex justify-content-between align-items-center" type="button" data-bs-toggle="collapse" data-bs-target="#servicePickerCollapse" aria-expanded="true" aria-controls="servicePickerCollapse">
                                    <span><i class="bi bi-list-ul me-2"></i> Choose Services</span>
                                    <i class="bi bi-chevron-down"></i>
                                </button>
                                <div class="collapse show mt-3" id="servicePickerCollapse">
                                    <div class="row g-3" id="serviceContainer">
                                        <!-- Generated by JS -->
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="mt-4">
                            <h5 class="mb-3">Selected Services</h5>
                            <div id="selectedServiceList" class="list-group mb-3">
                                <div class="list-group-item text-muted">No services selected yet.</div>
                            </div>
                        </div>

                        <div class="mt-4 text-end">
                            <button class="btn btn-primary next-step" disabled>Next <i class="bi bi-arrow-right"></i></button>
                        </div>
                    </div>

                    <!-- Step 2: Your Details -->
                    <div class="step-content" data-step="2">
                        <h4 class="mb-3">Your Information</h4>
                        <p class="text-muted">Enter your contact details and choose a date and time.</p>
                        <div class="row g-3">
                            <div class="col-lg-6">
                                <form id="detailsForm">
                                    <div class="row g-3">
                                        <div class="col-12">
                                            <label class="form-label">Full Name <span class="text-danger">*</span></label>
                                            <input type="text" class="form-control" id="patientName" placeholder="e.g., John Doe" required>
                                            <div class="invalid-feedback">Please enter your full name.</div>
                                        </div>
                                        <div class="col-12">
                                            <label class="form-label">Phone Number <span class="text-danger">*</span></label>
                                            <input type="tel" class="form-control" id="patientPhone" placeholder="+234 801 234 5678" required>
                                            <div class="invalid-feedback">Please enter a valid phone number.</div>
                                        </div>
                                        <div class="col-12">
                                            <label class="form-label">Email Address</label>
                                            <input type="email" class="form-control" id="patientEmail" placeholder="john@example.com">
                                        </div>
                                        <div class="col-12">
                                            <label class="form-label">Additional Notes (optional)</label>
                                            <textarea class="form-control" id="patientNotes" rows="3" placeholder="Any special requirements?"></textarea>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="col-lg-6">
                                <div class="bg-light rounded p-4 h-100">
                                    <h5 class="mb-3">Appointment Schedule</h5>
                                    <div class="mb-3">
                                        <label class="form-label">Preferred Date <span class="text-danger">*</span></label>
                                        <input type="date" class="form-control" id="appointmentDate" min="">
                                    </div>
                                    <div>
                                        <label class="form-label">Preferred Time <span class="text-danger">*</span></label>
                                        <div class="row g-2" id="timeSlotContainer">
                                            <!-- Generated by JS -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="mt-4 d-flex justify-content-between">
                            <button class="btn btn-outline-secondary prev-step"><i class="bi bi-arrow-left"></i> Back</button>
                            <button class="btn btn-primary next-step">Next <i class="bi bi-arrow-right"></i></button>
                        </div>
                    </div>

                    <!-- Step 3: Review & Pay -->
                    <div class="step-content" data-step="3">
                        <h4 class="mb-3">Review & Confirm</h4>
                        <p class="text-muted">Verify your selected services and payment details.</p>
                        <div class="row g-3">
                            <div class="col-lg-6">
                                <div class="bg-light rounded p-4">
                                    <h5 class="mb-3">Appointment Summary</h5>
                                    <div class="mb-3"><strong>Services</strong><div id="summaryServiceList" class="mt-2"></div></div>
                                    <div class="summary-item"><span>Date</span><span id="summaryDate">-</span></div>
                                    <div class="summary-item"><span>Time</span><span id="summaryTime">-</span></div>
                                    <div class="summary-item"><span>Patient</span><span id="summaryPatient">-</span></div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="bg-light rounded p-4">
                                    <h5 class="mb-3">Payment Breakdown</h5>
                                    <div class="summary-item">
                                        <span>Services</span>
                                        <span id="paymentServiceAmount">₦0.00</span>
                                    </div>
                                    <div class="summary-item">
                                        <span>Service Charge</span>
                                        <span id="paymentServiceFee">₦0.00</span>
                                    </div>
                                    <div class="summary-item">
                                        <span>VAT</span>
                                        <span id="paymentVat">₦0.00</span>
                                    </div>
                                    <div class="summary-item">
                                        <strong>Total</strong>
                                        <strong id="paymentTotal">₦0.00</strong>
                                    </div>
                                    <div class="form-check mt-3">
                                        <input class="form-check-input" type="checkbox" id="termsCheck" required>
                                        <label class="form-check-label" for="termsCheck">I agree to the <a href="#" class="text-primary">Terms & Conditions</a> and authorize payment.</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="mt-4 d-flex justify-content-between">
                            <button class="btn btn-outline-secondary prev-step"><i class="bi bi-arrow-left"></i> Back</button>
                            <button class="btn btn-success" id="payBtn">Pay Now <i class="bi bi-credit-card"></i></button>
                        </div>
                    </div>

                    <!-- Step 4: Confirmation with Receipt -->
                    <div class="step-content" data-step="4">
                        <div class="text-center mb-4">
                            <i class="bi bi-check-circle-fill text-success display-4"></i>
                            <h3 class="mt-2">Payment Successful!</h3>
                            <p class="text-muted">Your appointment has been confirmed.</p>
                        </div>

                        <!-- Receipt Container -->
                        <div id="receiptContainer">
                            <div class="receipt-header">
                                <!-- Logo placeholder – replace with actual logo URL -->
                                <img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect fill='%230066CC' width='100' height='100'/%3E%3Ctext x='50' y='55' font-size='40' text-anchor='middle' fill='white' font-family='Arial'%3E🏥%3C/text%3E%3C/svg%3E" alt="Maraba Hospital Logo" class="receipt-logo">
                                <h2 class="receipt-title">Maraba Charity Hospital</h2>
                                <div class="receipt-subtitle">Diagnostic & Laboratory Services</div>
                            </div>

                            <div class="verification-code-box">
                                <div style="font-size:13px; color:#666; margin-bottom:5px;">Verification Code</div>
                                <div class="code" id="receiptCode">APT-2024-XXXX</div>
                            </div>

                            <div class="receipt-row">
                                <span class="receipt-label">Service</span>
                                <span class="receipt-value" id="receiptService">-</span>
                            </div>
                            <div class="receipt-row">
                                <span class="receipt-label">Date</span>
                                <span class="receipt-value" id="receiptDate">-</span>
                            </div>
                            <div class="receipt-row">
                                <span class="receipt-label">Time</span>
                                <span class="receipt-value" id="receiptTime">-</span>
                            </div>
                            <div class="receipt-row">
                                <span class="receipt-label">Patient</span>
                                <span class="receipt-value" id="receiptPatient">-</span>
                            </div>
                            <div class="receipt-row">
                                <span class="receipt-label">Phone</span>
                                <span class="receipt-value" id="receiptPhone">-</span>
                            </div>
                            <div class="receipt-row" style="border-top:2px solid #0066CC; margin-top:10px; padding-top:10px;">
                                <span class="receipt-label">Amount Paid</span>
                                <span id="receiptAmount" class="receipt-value" style="font-size:18px; color:#0066CC;">₦0</span>
                            </div>

                            <div class="receipt-footer">
                                <p>123 Street, Abuja, Nigeria | +012 345 67890 | info@example.com</p>
                                <p style="font-size:12px;">This is a system-generated receipt. Please keep for your records.</p>
                            </div>
                        </div>

                        <div class="text-center mt-4">
                            <button class="btn btn-primary me-2" onclick="downloadReceiptPNG()">
                                <i class="bi bi-download"></i> Download Receipt
                            </button>
                            <a href="{{ route('home') }}" class="btn btn-outline-secondary"><i class="bi bi-house"></i> Home</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

<!-- Payment Loading Overlay -->
<div class="payment-overlay" id="paymentOverlay">
    <div class="spinner-border text-primary mb-3" style="width: 4rem; height: 4rem;"></div>
    <h4>Processing Payment...</h4>
    <p class="text-muted">Please wait, do not close this window.</p>
</div>

@endsection