<?php

return [
    'public_path' => public_path(),
    'base_path' => null,
    'host' => 'localhost',
    'protocol' => 'http',
    'http_timeout' => 30,
    'ssl_verify_peer' => false,
    'ssl_verify_peer_name' => false,
    'ssl_verify_host' => false,
    'chroot' => base_path(),
    'allowed_protocols' => ['file://', 'http://', 'https://'],
    'enable_remote' => false,
    'enable_javascript' => false,
    'enable_php' => false,
    'enable_html5_parser' => false,
    'temp_dir' => sys_get_temp_dir(),
    'font_dir' => storage_path('fonts/'),
    'font_cache' => storage_path('fonts/'),
    'pdf_backend' => 'CPDF',
    'default_media_type' => 'screen',
    'default_paper_size' => 'a4',
    'margin_bottom' => 0,
    'margin_left' => 0,
    'margin_right' => 0,
    'margin_top' => 0,
    'orientation' => 'portrait',
    'isPhpEnabled' => false,
    'isDpiAware' => false,
    'defaultFont' => 'serif',
    'dpi' => 96,
    'enable_font_subsetting' => false,
    'pdf_rendering_backend' => 'auto',
];
